import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { ClientProvider } from "@/components/providers/ClientProvider";

const Pretendard = localFont({
  src: "../static/fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${Pretendard.className} w-screen flex justify-center min-h-screen bg-primary-200`}
      >
        <ClientProvider>
          <div className="w-[400px] bg-neutral-0">{children}</div>
        </ClientProvider>
      </body>
    </html>
  );
}
